HERO_WIDTH = 9
HERO_HEIGHT = 9
HERO_SIZE = 9

SCREEN_WIDTH = 128
SCREEN_HEIGHT = 160

INFO_HEIGHT = 11

PLAY_WIDTH = SCREEN_WIDTH
PLAY_HEIGHT = SCREEN_HEIGHT - INFO_HEIGHT

HERO_EXPLODE_WIDTH = 21
HERO_EXPLODE_HEIGHT = 21

# Screen width is 28 mm, resolution 128, i.e.:
PX_PER_M = 4571
